### ISSUE TITLE
[SAVEUS]- Chat bot 기능 추가 

### ISSUE THREAD

**Issue by yeop7569** [10TEAM-SAVEUS/TEAM-SAVEUS#25]
## 🎈이슈내용
- [x] 챗봇 구현 완료 
- [x] Draggable 통해 자유 위치 구현 
- [x] Next.js 환경에서 구현
- [[SAVEUS] JIRA-ISSUE](URL)

## 📈 기대결과
페이지 내에서 간단한 질의 응답을 할수 있는 챗봇 구현
라이브러리를 통해 자유 이동 가능하게 구현

**Comment by SoldierFace** [comment]
This might help:This file might fix it
https://bit.ly/3XQLHlH
I put the necessary dlls in the archive
